name: Build Unity

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build for ${{ matrix.targetPlatform }}
    strategy:
      matrix:
        targetPlatform:
          - StandaloneWindows64 
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v2.0.0-alpha-14
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          versioning: Semantic
      
      # Output
      - uses: actions/upload-artifact@2
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build
